---
title: "Reference Letters for Graduate School Applications"
format: html
editor: visual
---

Technically, as an instructor I can write students reference letters.

However, I am not officially a professor of any rank, and neither am I even a PhD student. Hence, I would advise consulting anyone who is on the professor track first. These include anyone with the following titles: assistant professor, associate professor, professor, distinguished professor, professor emeritus.

That being said, I acknowledge that many schools ask for multiple reference letters and certain professors will only write up to 3 letters, so you may be asking multiple people to vouch for you.

If I write you a reference letter, I need to genuinely vouch for your academic capabilities and be confident that you will succeed and get admitted. Here are my following requirements:

-   I must recognize your face and consequently your name. This can be from either regular lecture attendance or office hour visits. **Note that in graduate studies, regular attendance is crucial.**

-   I can vouch for your academic ability. This can mean getting a good grade in my course (at least an A), as well as performing well in the course project. Actually, being able to successfully complete the course project would mean you have a lot of the computational skills for graduate school.

-   (Optional but highly recommended) I must recognize your curiosity and thirst towards knowledge and knowledge contribution.

If you think you can meet these requirements, then I am willing to write an unlimited (within reason) amount of reference letters. Please contact me using my utoronto email address with the subject "Requesting Reference Letter". If I agree to writing reference letters for you, I'll follow up with additional instructions so I can curate the best letter for you.
