---
title: "Agenda"
format: html
editor: visual
---

Plans may change. This includes what we have completed week by week.

## Week 1

**Lecture (January 5):** Generating Random Variables (Inverse Transform)

In this lecture we covered all of the inverse-transform methods, although we skipped the recursive question regarding the logarithmic distribution due to time.

[Live January 5 code](../coding/live_lecture/jan5_code.R)

The typo was that I used `n` when I should have used `m` when generating from the uniform distribution.

In the lecture I initially argued that we should be using the `floor()` function (for the geometric distribution question), but then in my past notes I used `ceiling()`. Analysing the answer a bit further, it is likely the case that we must take the `ceiling()` because the geometric distribution has a support that starts at `1`, not `0`, and thus a ceiling guarantees the value of $x$ will be at least 1.

The first thing we proved in class is admittedly an analysis proof; I handwaved it. Since MAT337 is not a pre-requisite, you do not need to know the proof. However, you should understand how to do the rest of the proofs in this unit.

**Tutorial (Cancelled; Recording Instead):** Practice questions for preliminary Quiz 1

No assessments due, but the preliminary quiz is open. You should do it before it's too late!

## Week 2

**Lecture (January 12):** Generating Random Variables

Lecture was relatively smooth, but there was an issue with zoom where my screen automatically stopped sharing my screen.

We finished unit 1!

[Live January 12 code](../coding/live_lecture/jan12_code.R)

**Tutorial (January 13):** Practice questions for Quiz 2

No assessments due, but the preliminary quiz is open. You should do it before it's too late!

## Week 3

**Lecture (January 19):** Monte Carlo Integration

We finished the material included in the first term test and the first quiz. That being said, it is highly recommended to keep following the material, as the rest of the unit is quite helpful for understanding the big picture. (Also, just a warning that test 2 is harder than test 1 due to the nature of the material.)

Towards the end I had a typo and a student kindly corrected me after lecture ended. In lecture, I did

`var <- mean((hit - est)^2)/n^2`

when really, I should have done

`var <- mean((hit - est)^2)/n`

because the `mean()` accounts for the division by `n` once.

Edit January 23: for some reason in my memory I recall that I misspoke "any estimator" instead of "any sample mean estimator" for the CLT... Hopefully you knew what I meant.

[Live January 19 code](../coding/live_lecture/jan19_code.R)

**Tutorial (January 20):** Practice questions for Quiz 3

Deadlines:

-   Preliminary Quiz is due on Tuesday January 20 (11:59pm).

-   Quiz 2 is due on Friday January 23 (11:59pm).

## Week 4

**Lecture (January 26):** Monte Carlo Integration

**Tutorial (January 27):** Practice questions for Term Test 1

Deadlines:

-   Quiz 3 is due on Friday January 30 (11:59pm).

## Week 5

**Lecture (February 2):** Term Test 1

**Tutorial (February 3):** Additional Monte Carlo practice questions. (This is the second half of unit 2. It is found under quiz 3 information.)

Deadlines:

-   Group formation is due on Wednesday February 4 (11:59pm).

## Week 6

**Lecture (February 9):** Monte Carlo Integration / Monte Carlo Methods in Inference

**Tutorial (February 10):** Practice questions for Quiz 4

Deadlines:

-   Proposal is due on Wednesday February 11 (11:59pm).

## Week 7

READING WEEK! ENJOY YOUR HOLIDAY!

## Week 8

**Lecture (February 23):** Monte Carlo Methods in Inference

**Tutorial (February 24):** Practice questions for Quiz 5

Deadlines:

-   Quiz 4 is due on Friday February 27 (11:59pm).

-   Basic implementation check is due on Wednesday February 25 (11:59pm).

## Week 9

**Lecture (March 2):** Re-sampling Techniques

**Tutorial (March 3):** Practice questions for Term Test 2

Deadlines:

-   Quiz 5 is due on Friday March 6 (11:59pm).

-   Package compiling is due on Wednesday March 4 (11:59pm).

## Week 10

**Lecture (March 9):** TERM TEST 2

**Tutorial (March 10):** \[Tutorial may be cancelled! Take a break!\]

Deadlines:

-   Website prototype is due on Wednesday March 11 (11:59pm).

## Week 11

**Lecture (March 16):** Probability density estimation / Optimization

**Tutorial (March 17):** \[No plan yet...\]

Deadlines:

-   Quiz 6 is due on Friday March 20 (11:59pm).

## Week 12

**Lecture (March 23):** Optimization

**Tutorial (March 24):** Practice questions for Quiz 7

Deadlines:

-   Quiz 7 is due on Friday March 27 (11:59pm).

-   Final implementation is due on Wednesday March 25 (11:59pm).

## Week 13

**Lecture (March 30):** Review/Grace Period

**Tutorial (March 31):** Final Exam Review
