---
title: "Lectures"
format: html
editor: visual
---

I understand the lecture times are late at night, and many people may be sick during the winter session. There will be a zoom link for the live lectures, although I encourage students to arrive physically as I will not be monitoring the zoom chat (and it is harder for me to answer questions.)

Solutions to lecture notes will be posted upon completion of a section. Recordings may be uploaded on Quercus but no promises (in case a file gets corrupted, quality is poor, etc.)

I recommend against rushing everything until last second. The assessments will be difficult if you do not come to lecture regularly and ask questions. The examinations should be reasonable otherwise.

# Unit 1: Generating Random Variables

[Lecture Notes](lecture_notes/Unit1_Slides_nosol.pdf)

[Lecture Notes (Solution Version)](lecture_notes/Unit1.pdf)

The codes below were my prepared notes. Some of them differ significantly from lecture, where I am coding on the spot. (The live code can be found in the agenda.)

[R Code - Inverse Transform](../coding/lecture/unit1_inverse_transform.R)

[R Code - Acceptance Rejection](../coding/lecture/unit1_acceptreject.R)

[R Code - Convolution](../coding/lecture/unit1_convolution.R)

[R Code - Mixtures](../coding/lecture/unit1_mixtures.R)

Prioritize the quiz preparation questions and the quiz questions themselves, but additional recommended additional problems (posted on Quercus)

Practice 1, 2, 3, 4.

You do not need to worry about the Box-Muller transformation (practice 4, problem 3), as I decided to not cover this.

------------------------------------------------------------------------

# Unit 2: Monte Carlo Integration

[Lecture Notes](lecture_notes/Unit2_Slides_nosol.pdf)

There is a typo in the above lecture notes. For instance, I forgot a coefficient 2 when adding for the covariance term (antithetic variable section). It is fixed in the solution version, which also includes additional questions.

[Lecture Notes (Solution Version)](lecture_notes/Unit2.pdf)

[R Codes](../coding/lecture/unit2_montecarlo.R)

Some of the solutions, particularly the additional extra problems, were only done in live lectures and are not included in the above R codes.

For term test 1, additional recommended practice (posted on Quercus) is practice 5, questions 1-4. However, you don't need to worry about computing the variance until the second term test.

For term test 2, make sure you do the rest of practice 5 (including computing the variance), 6, 7, 8.

------------------------------------------------------------------------

# Unit 3: Monte Carlo Methods in Inference

Lecture Notes - TBA; recently removed (need to change)

Lecture Notes (Solution Version) - TBA

R Codes - TBA

------------------------------------------------------------------------

# Unit 4: Resampling Techniques (includes Permutation Tests)

Lecture Notes - TBA

Lecture Notes (Solution Version) - TBA

R Codes - TBA

------------------------------------------------------------------------

# Unit 5: Probability Density Estimation

[Lecture Notes](lecture_notes/Unit5_Slides_nosol.pdf)

Lecture Notes (Solution Version) - TBA

R Codes - TBA

------------------------------------------------------------------------

# Unit 6: Optimization

Lecture Notes - TBA; need to reupload

Lecture Notes (Solution Version) - TBA

R Codes - TBA

------------------------------------------------------------------------

If you saw an earlier version of this website, you've noticed I removed covering MCMC methods. This is because most instructors advised not adding too much. That being said, if I have an ambitious cohort I may re-add it! :D
