---
title: "Test Information"
format: html
editor: visual
---

I plan to have a clear outline of topics I expect students to know for the tests and supply 2-3 practice tests of a similar difficulty.

In general, I believe if you know genuinely how to solve questions shown in lecture, tutorials, and practice problems, then I believe there should be no problem obtaining 80%+ in the course.

The main issue is that I want to cover a lot of material for this course. So don't leave everything to the last minute!

# Weekly Quercus Quizzes

The first quiz topics preliminary topics from STA256H5 and STA260H5. It will be available from the start of the course until January 20th. However, we recommend starting the quiz as early as possible; the due date is to accommodate for students that enroll in the course later.

The rest of the quizzes will be available from Thursday 12:00am to Friday 11:59pm. The best 5 out of 7 will be counted.

The Quercus quizzes are in the format of multiple choice, true or false, or fill in the blank (numerical answers).

## Quiz 1: Preliminary Quiz (Due January 20th)

[Quiz 1 Solutions](test/quiz1_sol.pdf)

For this quiz, you need to know the following concepts:

-   How to compute an expected value, variance, bias, and mean squared error for continuous random variables. It's even easier if you recognize well known continuous distributions: Gaussian (also known as normal), exponential, gamma, beta.

    -   You **should** know how to do this for discrete random variables as well, but it is not on the quiz.

-   Know the variance-bias decomposition of mean squared error.

-   Know how to compute confidence intervals.

-   Know how to derive likelihood functions and find the maximum likelihood estimator.

[Practice questions to prepare for quiz 1.](practice/quiz1_practice.pdf)

Unlike the practice questions, you may be given the actual population parameter (i.e., $\beta = 2$) such that you can insert your fill-in-the-blank answer for the mean, variance, bias, and MSE. You should hold onto your original equation (without inserting $\beta$) as the value provided will change.

## Quiz 2: Generating Random Variables

[Quiz 2 Solutions](test/quiz2_sol.pdf)

Availability period: January 22-23

[Practice questions to prepare for quiz 2.](practice/quiz2_practice.pdf)

## Quiz 3: Monte Carlo Integration

[Quiz 3 Solutions](test/quiz3_sol.pdf)

Availability period: January 29-30

[Practice questions to prepare for quiz 3.](practice/quiz3_practice.pdf)

Note that this quiz only covers the first half of the second unit. In retrospect, I should have created eight quizzes instead of seven, but I did not want to give too many assessments the same week of the test.

Nonetheless, the below material is needed for term test 2.

[Practice questions for second half of unit 2.](practice/unit2_extraprac.pdf)

There is a typo in 2.a) where I say Uniform(0, 1), but I meant Uniform(0, 10).

## Quiz 4: Monte Carlo Methods in Inference

[Quiz 4 Solutions](test/quiz4_sol.pdf)

Note that for the quiz, I should have said "Monte Carlo estimate(s) for the MLE/UMVUE". This did not affect students' scores, as given the m/c options, it is clear that only the parametric bootstrapped samples were constructed but not the total average of all of them.

Availability period: February 26-27

[Practice questions to prepare for quiz 4.](practice/quiz4_practice.pdf)

## Quiz 5: Re-sampling Techniques

[Quiz 5 Solutions](test/quiz5_sol.pdf)

Availability period: March 5-6

[Practice questions to prepare for quiz 5.](practice/quiz5_practice.pdf)

## Quiz 6: Probability density estimation

[Quiz 6 Solutions](test/quiz6_sol.pdf)

Availability period: March 20-27

There will be no practice quiz for probability density estimation. You can just rely on the lecture slides.

## Quiz 7: Optimization

[Quiz 7 Solutions](test/quiz7_sol.pdf)

Availability period: March 26-27

[Practice questions to prepare for quiz 7.](practice/quiz7_practice.pdf)

# Term Tests and Examinations

## Coding Expectations

You are expected to know how to code in `R` by hand for the term tests. You do not need to memorize a bunch of different functions and perfectly make plots. Most of the coding in `R` is to demonstrate that you know how to write the algorithms taught in lecture. In particular, students should be familiar with the following functions and how to do the following tasks:

-   Setting a seed: `set.seed()`

-   Variable assignment, either `<-` or `=`

-   Initialize a vector: `x <- c()`

-   Basic math operators & common functions

    -   Addition: `+`

    -   Subtraction: `-`

    -   Multiplication: `*`

    -   Division: `/`

    -   Exponents: `^` or `**`

    -   Exponential: `exp()`

    -   Natural Logarithm: `log()`

-   Basic logic operators (i.e., or: `|`, and: `&`, as well as `>=`, `==`, `<=`, `>`, `<`)

-   Simulate from a standard uniform distribution `runif()` and standard Gaussian `rnorm()`. **We will give function and argument descriptions IF we require anything else similar to these.** Examples of what we would PROVIDE, IF NEEDED, are below:

    -   Uniform(a, b), N(mu = a, sigma = b), etc.

    -   density, `dnorm()`, quantile `qnorm()`, cdf `pnorm()`, etc.

    -   Simulations from other distributions such as gamma `rgamma()`, beta `rbeta()`, etc.

-   Write if/else statements, and `ifelse()`

-   Write for and while loops

-   Write functions and include arguments and the `return()` statement(s)

-   Writing comments; use `#` before writing them

-   **(Not for term test 1)** Loading a library: `library(package_name)`

-   **(Not for term test 1)** Initializing matrices `matrix()`

-   **(Not for term test 1)** Operations that can be performed on matrices. For example, if `X` is a matrix than `exp(X)` will apply the exponential function on every single value within the matrix `X`.

-   **(Final examination only)** How to use `optimize()` and `optim()`. 

## Term Test 1

[SOLUTIONS FOR THE TERM TEST](test/Test1Solutions.pdf)

[Practice Test Version A](practice/STA380_test1_practiceA.pdf) \| [Practice Test Version B](practice/STA380_test1_practiceB.pdf)

The [formula sheet](practice/Test1_FormulaSheet.pdf) for term test 1 will be different from term test 2 and the final exam.

Practice tests are for students to get a general idea of the topics that may be asked and expectations.

For this term test, students should be comfortable with the following:

-   Pre-requisite material that have been shown during lecture (i.e., cdf, pdf, expected value, etc.)

-   All derivations and `R` codes regarding the inverse-transform and acceptance-rejection method as outlined in lecture and practice problems.

-   Given a transformation or convolution (i.e., if provided the relationship between a standard Gaussian and a chisquare distribution), students should be able to write in `R` code how to generate the requested distribution.

-   Understand how mixture models work for generating random variables, the code used to generate them, and the difference between mixture and convolutions.

-   Introductory Monte Carlo methods for numerically estimating integrals (Section 1 of Unit 2 slides.) Both the written algorithm and how to code.

-   Understanding how to use the SLLN (mostly for simple Monte Carlo methods).

Students will NOT be asked to do or remember the following:

-   Derive a proof that heavily relies on analysis; i.e., the first proof done in lecture.

-   Trick questions regarding whether the inverse-transform or the acceptance-rejection method is applicable or preferred in certain cases.

-   Memorize all different combinations of transformations and convolutions between distributions; these will be supplied. Consult the practice test for examples.

-   The following definitions: convergence in probability and almost sure convergence.

-   Plotting in `R`.

**Recommended preparation:**

In order, where the first items are highly recommended.

-   Complete both practice tests.

-   Redo the practice quizzes.

-   Redo the lecture slides (proof questions).

-   Redo the tutorial problems.

-   Redo the lecture slides (example questions).

-   See additional practice problems 2, 3, 4, and 5 — but for problem 5, do only questions 1 and 2. (Posted on Quercus only.) Do not worry about the box-muller transformation.

**My approach for making problems:**

If you are unsatisfied with the amount of practice questions, part of the beauty of this course is it’s quite feasible to make your own problems and double check with computations. You will learn a decent amount by trying to use these methods with different distributions that you pick online, especially to understand when inverse-transformation should be used and when acceptance-rejection is better.

When I was making questions for the inverse-transform method, I essentially looked at undergraduate textbooks in 2nd probability for some simple distributions with a closed form cdf to try to simulate values.

For the acceptance-rejection method, I looked at common probability distributions that do not have a proper closed form and tried to simulate from them.

Convolution methods are straightforward; I would recommend attempting every type of convolution I listed on the lecture slides to simulate.

Similarly, you may try different combinations of mixtures and simulate against the true density.

Simple Monte Carlo methods are the easiest to make problems for, as we’re essentially estimating integrals. Simply search up any integral practice problem sheet of a first-year calculus class and instead of integrating, try to use the simple algorithm and compare to the true integral. For a more practical use case, you can just search for integrals without a closed form.

## Term Test 2

[SOLUTIONS FOR THE TERM TEST](test/Test2Solutions.pdf)

[Practice Test Version A](practice/STA380_test2_practiceA.pdf) \| [Practice Test Version B](practice/STA380_test2_practiceB.pdf)

DO NOT BRING YOUR OWN FORMULA SHEET.

The [formula sheet](practice/Test2_FormulaSheet.pdf) for term test 2 contains less `R` codes. At this point, we expect you to have practiced more.

For this term test, students should be comfortable with the remainder of the content from Unit 2 and the entirely of Unit 3. These include:

-   The Monte Carlo hit or miss approach.

-   Facts regarding the empirical CDF.

-   Importance Sampling approach. (We will choose the importance function for you.)

-   Antithetic variables approach.

-   Compute Monte Carlo estimates for the mean, standard error, MSE, confidence levels, type-I error, type-II error.

-   Compute Monte Carlo estimates for any provided expression.

-   Understand what a *actually* p-value is.

Students will NOT be asked to do or remember the following:

-   The following definitions: weak convergence, convergence in distribution.

-   Derive the UMVUE. If the UMVUE is mentioned, it will be supplied.

-   Derive the rejection region (RR) using the NP Lemma. If you are asked to write code for estimating type-I or type-II error, you will be explicitly given the rejection region, similar to the practice tests.

This test will be calculated out of 27 points. This test has bonus questions, hence, it is possible to get an additional 3 points. The bonus questions are relevant to STA256/STA260 material.

**Recommended preparation:**

In order, where the first items are highly recommended.

-   Complete both practice tests.

-   Practice questions for second half of unit 2 and quiz 4.

-   Redo the lecture slides (example questions).

-   Redo Quercus quiz 4.

See additional practice problems 5, 6, 7, and 8 — but for problem 5, do only questions 3 to 6. (Posted on Quercus only.)

## Final Exam

[Practice Final Exam Version A](practice/STA380_final_exam_A.pdf) \| [Practice Final Exam Version B](practice/STA380_final_exam_B.pdf)

Click here to see the attached [formula sheet](practice/STA380_Final_FormulaSheet.pdf).

The final exam has been approved and the details of this page are accurate.

In general, the final exam will be cumulative, but with extra weight towards content past the first two term tests.

You do not need to know Unit 5 for the final exam. It is included in the formula sheet in case you were paranoid.

### Final Exam Outline

Below is a detailed what students should expect from the actual term test.

Question 1 \[18 marks\]: EM algorithm computation (Unit 6). There should be no surprise here.

Question 2 \[10 marks\]: Coding question either from Unit 4 or Unit 6. You will likely have a sufficiently prepared `R` coding formula sheet to answer this question.

Question 3 \[10 marks\]: Proof question related to Unit 4 that you have not seen before. Practice exams A and B will have similar, "never seen" before proof questions.

Question 4 \[5 marks\]: Question related to Unit 1. May either be a computational or a proof question. You should have had adequate preparation of Unit 1 material from the first term test.

Question 5 \[7 marks\]: Question related to Unit 2 material. May either be a computational or a proof question. You should have had adequate preparation of Unit 2 material from both the first and second term test.

Question 6 \[10 marks\]: Either a proof question related to Unit 2 material OR a short answer question explaining differences between some concepts of the course. Refer to the practice exams for an example of either.

### Formula Sheet Policy (FINAL EXAM ONLY)

We will supply a formula sheet with common distribution functions (exponential, gamma, normal) and some extra useful information.

For the `R` coding portion, students are allowed to bring their own formula sheet.

You may bring one (1) formula sheet to the FINAL exam, subject to all of the following rules.

[**Physical Format**]{.underline}

-   Exactly one standard letter-size page (8.5″ × 11″)

-   Double-sided (both sides may be used)

-   Can be typed, handwritten, or a combination of both

-   Written or printed in English only

[**Permitted Content**]{.underline}

The formula sheet may contain `R` programming content ONLY, including:

-   `R` function calls

-   `R` syntax reminders

-   Short comments explaining the purpose of `R` code

-   Common R workflows or templates (e.g., loops, function definitions, plotting structure). You may copy all codes relating to the EM algorithm, Newton-Rapshon algorithm, KS permutation tests, etc.

[**Prohibited Content**]{.underline}

The formula sheet must NOT contain:

-   Mathematical formulas written in standard mathematical notation (e.g., integrals, summations, likelihoods, distributions written symbolically)

-   Statistical definitions or theory stated in words (e.g., "the MLE is…", "a p-value is…")

-   Step-by-step algorithms written in plain English

-   Exam-style answers, worked examples, or interpretations

**Rule of thumb:** If it is not valid `R` code or an `R` comment directly explaining that code, it does not belong on the formula sheet.

[**Other Policies**]{.underline}

You are allowed to share, copy, or reproduce another student’s formula sheet.

The instructor will inspect formula sheets during the exam, confiscate any sheet that violates these rules, and treat violations as an academic integrity issue.
