---
title: "Tutorial Information"
format: html
editor: visual
---

**All notes and information provided on this page are managed by the teaching assistant, Ting Lin.**

<hr style="border:0; border-top:2px solid #ccc; margin:1.5em 0;">

**Tutorial 1:**

The first tutorial was cancelled because currently Ting is out of the country. However, the recording is on Quercus in the same location as the lecture recordings.

[Tutorial 1 Notes](tutorial/STA380_TUT1.pdf)

<hr style="border:0; border-top:2px solid #ccc; margin:1.5em 0;">

**Tutorial 2:**

Due to the limited time, we were unable to cover all the questions in Tutorial 2. Please try the remaining questions on your own since this will be very helpful for the test/exam.

[Tutorial 2 Notes](tutorial/STA380_TUT2.pdf)

<hr style="border:0; border-top:2px solid #ccc; margin:1.5em 0;">

**Tutorial 3:**

[Important updates:]{style="color:red; font-weight:bold; font-size:1em;"}

[There were a few typos in the solutions for Question 1. The instructor has updated them, so please refer to the latest version of Practice 3.]{style="color:red; font-weight:bold; font-size:1em;"}

During the tutorial, I didn’t notice the issue. By the time I realized where the typos were at the end of the tutorial, most of the students had already left. So please don’t worry if you didn’t understand the issue. I will go over this question, including the Monte Carlo estimation, next time.

I have also updated the notes for Tutorial 3 as shown below.

[Tutorial 3 Notes](tutorial/STA380_TUT3.pdf)

<hr style="border:0; border-top:2px solid #ccc; margin:1.5em 0;">

**Tutorial 4:**

The recording of tutorial 4 has been posted on Quercus, please post your questions on piazza if needed.

God luck for the Term Test 1. :)

[Tutorial 4 Notes](tutorial/STA380_TUT4.pdf)

<hr style="border:0; border-top:2px solid #ccc; margin:1.5em 0;">

**Tutorial 5:**

These are the notes for Tutorial 5. I would like to clarify part (c) of Question 1 again, I mentioned that $$g(x)=10*u_i*ln(u_i)$$ and one student asked why.

Here is the explanation: $$\theta=\int_0^{10} xln(x)dx=E[g(X)]$$ and by MC method, we rewrite it as

$$\theta=10 \int_0^{10} \frac{1}{10}xln(x)dx = \int_0^{10} 10*\frac{1}{10}xln(x)dx =  E_{U(0,10)}[g(X)]=\int g(X) * \frac{1}{10} dx$$

which is the $g(X)$ times the density of $Uniform(0,10)$, $\frac{1}{10}$.

And for proof question, if you used $E[X_i]$ or $Var[X_i]$, that is fine as well.

[Tutorial 5 Notes](tutorial/STA380_TUT5_new.pdf)

<hr style="border:0; border-top:2px solid #ccc; margin:1.5em 0;">
